#class_name ProjectHammer
extends Node

enum CraftStatistic {
	#Modifiable stats
	AUGMENT_SLOTS,
	PERSONNEL_CAPACITY,
	CARGO_CAPACITY,
	CARGO_TRANSFER_SPEED,
	MASS,
	ENGINE_THRUST,
	THRUSTER_THRUST,
	ENERGY_PRODUCTION,
	ENERGY_DEMAND,
	MAX_BATTERY_CHARGE,
	#Dependant stats
	BATTERY_CHARGE,
	ENERGY_SATISFACTION,
	SYSTEM_EFFICIENCY,
}
